name: ctest

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

#    container:
#        image: koreader/koappimage:0.1.7
#        options: --user root
#    with:
#        username: $DOCKER_USERNAME
#        password: $DOCKER_PASSWORD
        
    env:
        EMULATE_READER: 1
        # this is for shellcheck 0.4.5 and lower; can be removed for 0.4.6
        LC_ALL: en_US.UTF8

    steps:
      - name: Add 32bit arch
        run: sudo dpkg --add-architecture i386

      - name: install shfmt
        run: sudo snap install shfmt

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends build-essential git patch wget unzip gettext autoconf automake cmake libtool nasm ragel luarocks libsdl2-dev libssl-dev libffi-dev libsdl2-dev libc6-dev-i386 xutils-dev linux-libc-dev:i386 zlib1g:i386 shellcheck

      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - name: Cache deps
#        uses: actions/cache@v2
#        with:
#            path: |
#                /home/ko/.ccache
#                base
#            key: deps-{{ arch }}-{{ checksum ".ci/install.sh" }}-{{ checksum ".ci/helper_luarocks.sh" }}

#      - name: need to init some stuff first or git will complain when sticking in base cache
#        run: cd "$GITHUB_WORKSPACE" && git submodule init base && git submodule update base && pushd base && git submodule init && git submodule update && popd

#      - name: cache check
#        run: pushd base && git_rev_base=$(git describe HEAD) && popd && echo $git_rev_base && echo $git_rev_base >git-rev-base

#      - name: Cache base
#        uses: actions/cache@v2
#        with:
#            path: |
#                /home/ko/bin
#                /home/ko/.luarocks
#                install
#            key: build-{{ arch }}-{{ checksum "git-rev-base" }}

#      - name: setup env
#        run: echo 'export PATH=${HOME}/bin:${PATH}' >> $BASH_ENV

      - name: kodev activate
        run: ./kodev activate

      - name: install luarocks packages
        run: luarocks --local install luafilesystem ansicolors busted luacheck lanes ldoc luacov

      - name: kodev fetch third party
        run: ./kodev fetch-thirdparty

      - name:  build
        run: ./kodev build

      - name: check
        run: .ci/check.sh

      - name:  test
        run: ./kodev test front

      - name:  docs-and-coverage
        run: .ci/after_success.sh


