name: CI tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    env:
        EMULATE_READER: 1

    steps:
      - name: Add 32bit arch
        run: sudo dpkg --add-architecture i386

      - name: install shfmt
        run: sudo snap install shfmt

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends build-essential git patch wget unzip gettext autoconf automake cmake libtool libtool-bin nasm ragel luarocks libsdl2-dev libssl-dev libffi-dev libsdl2-dev libc6-dev-i386 xutils-dev linux-libc-dev:i386 zlib1g:i386 shellcheck luajit

      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - name: cache check
#        run: pushd base && git_rev_base=$(git describe HEAD) && popd && echo $git_rev_base && echo $git_rev_base >git-rev-base

#      - name: Cache deps
#        uses: actions/cache@v2
#        with:
#            path: |
#                $HOME/.ccache
#                $GITHUB_WORKSPACE/base
#            key: build-{{ arch }}-{{ checksum "git-rev-base" }}

#      - name: need to init some stuff first or git will complain when sticking in base cache
#        run: cd "$GITHUB_WORKSPACE" && git submodule init base && git submodule update base && pushd base && git submodule init && git submodule update && popd


      - name: install luarocks packages
        run: luarocks --local install ansicolors && luarocks --local install busted && luarocks --local install luacheck && luarocks --local install lanes && luarocks --local install ldoc && luarocks --local install luacov

      - name: luarocks path
        run: touch ${HOME}/.luarocks/config.lua && echo "LUA_PATH=$(luarocks path --lr-path)" >> $GITHUB_ENV && echo "LUA_CPATH=$(luarocks path --lr-cpath)" >> $GITHUB_ENV && echo "LUA_PATH=$(luarocks path --lr-bin)" >> $GITHUB_PATH

      - name: kodev fetch third party
        run: ./kodev fetch-thirdparty

      - name: check
        run: .ci/check.sh

      - name:  build
        run: ./kodev build

      - name:  test
        run: ./kodev test front

      - name:  coverage
        run: ./kodev cov


